runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "14.1"
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
    - uses: pnpm/action-setup@v2
      with:
        run_install: true
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - run: |
        rustup update
    - if: runner.os == 'macOS'
      id: mint
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: ${{ runner.os }}-mint-
    - if: runner.os == 'macOS'
      run: |
        brew install mint
    - if: runner.os == 'macOS' && steps.mint.outputs.cache-hit != 'true'
      run: |
        mint bootstrap
