included:
  - Application/Light/Sources
  - Application/Light Safari Extension/SafariWebExtensionHandler.swift
  - Components/Sources
  - Components/Tests
excluded:
  - Components/.build
disabled_rules:
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - trailing_comma
