name: iOS
on:
  push:
    branches:
      - main
  pull_request:
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: |
          pnpm run build
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.1"
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: |
          pnpm run fastlane:test
        working-directory: ./Application
