name: Release
on:
  push:
    branches:
      - main
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: |
          rustup update
      - run: |
          pnpm run build
      - uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: pnpm run release -r
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
