name: Release
on:
  push:
    branches:
      - main
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
      - run: |
          pnpm install --frozen-lockfile
      - run: |
          pnpm run build
      - uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: pnpm release -r
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
