name: Turbo
on:
  push:
    branches:
      - main
  pull_request:
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
      - run: npm install -g yarn
      - uses: borales/actions-yarn@v4
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn turbo run build
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
      - run: npm install -g yarn
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run turbo run lint
